on:
  workflow_dispatch:
  
jobs:
  build-site:
    runs-on: ubuntu-22.04
    steps:
    - name: install trunk
      run: cargo install trunk
    - name: build website
      run: trunk build --release
